services:
  mongodb:
    image: mongo:latest
    container_name: auth_mongodb
    networks:
      - dealership_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

networks:
  dealership_network:
    external: true  